name: Reusable workflow example

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v3
    - name: npm install and build webpack w/${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v3
      with:
        name: webpack artifacts
        path: public/
